### ISSUE TITLE
Central repository for NodeBots information

### ISSUE THREAD

**Issue by k45514n** [nodejs/hardware#6]
I've kind of dubbed this the NodeBots Ecosystem project

My call-to-action for the next meeting is to get together what I have on this project so far, and my ideas for what we can do to make it work and be a team project.

The fly-by is we need a site that shows the differences between the types and platforms of NodeBots, and guide new users toward a platform that meets their needs.

**Comment by dtex** [comment]
This could be a page on http://nodebots.io

The http://johnny-five.io/platform-support/ page could be very helpful.

Perhaps we could talk to @rwaldron / Bocoup (do you know anyone who works there?) about sharing data.

**Comment by mikeal** [comment]
Haha, Kassandra also works at Bocoup ;)

**Comment by k45514n** [comment]
I think @dtex was joking. Either way, yes, I worked a little on the initial run of the new j5 site and planned to use lessons learned and some of the awesome features @rwaldron has implemented.

**Comment by dtex** [comment]
I'm rarely serious

**Comment by mikeal** [comment]
oh, haha! :)

**Comment by Resseguie** [comment]
It would be nice to have it auto-generated from a central source like the johnny-five.io site.

**Comment by k45514n** [comment]
That's why I've been building a database first. That way we can deploy new information quickly. More info tomorrow when I get some time to write.

On Friday May 15, 2015 at 7:55 PM, David Resseguie notifications@github.com, wrote:
It would be nice to have it auto-generated from a central source like the johnny-five.io site.

**Comment by mikeal** [comment]
The NodeSchool website has a lot of pages built from Google Spreadsheets, so that's an option.
